name: drpy
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - numpy
  - scipy
  - matplotlib=3.2
  - proplot
  - xarray
  - netcdf4
  - pyyaml
  - pandas
  - pyproj
  - cartopy=0.18
  - pip
  - h5py
  - ipykernel
